# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8e7e81d205e32d26923e6da42669b2c8"
name = "rbx-bundle-app"
handle = "rbx-bundle-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "apifex-learning.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
